2025-07-20 16:17:39,126 ERROR: Exception on /reset_password_request [POST] [in /home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 540, in send
    message.send(connection)
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 482, in send
    connection.send(self)
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 177, in send
    self.host.sendmail(
  File "/usr/lib/python3.12/smtplib.py", line 861, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.12/smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
                   ^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.12/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.12/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/app/routes.py", line 230, in reset_password_request
    send_password_reset_email(user)
  File "/home/oslab/microblog/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/oslab/microblog/app/email.py", line 9, in send_email
    mail.send(msg)
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 539, in send
    with self.connect() as connection:
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 136, in __exit__
    self.host.quit()
  File "/usr/lib/python3.12/smtplib.py", line 993, in quit
    res = self.docmd("quit")
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.12/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.12/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2025-07-20 16:20:26,294 INFO: Microblog startup [in /home/oslab/microblog/app/__init__.py:45]
2025-07-20 16:21:04,474 ERROR: Exception on /reset_password_request [POST] [in /home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/app/routes.py", line 230, in reset_password_request
    send_password_reset_email(user)
  File "/home/oslab/microblog/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/oslab/microblog/app/email.py", line 9, in send_email
    mail.send(msg)
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 539, in send
    with self.connect() as connection:
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 127, in __enter__
    self.host = self.configure_host()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 144, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 343, in connect
    (code, msg) = self.getreply()
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
2025-07-20 16:21:55,745 ERROR: Exception on /reset_password_request [POST] [in /home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/app/routes.py", line 230, in reset_password_request
    send_password_reset_email(user)
  File "/home/oslab/microblog/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/oslab/microblog/app/email.py", line 9, in send_email
    mail.send(msg)
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 539, in send
    with self.connect() as connection:
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 127, in __enter__
    self.host = self.configure_host()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/oslab/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 144, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 343, in connect
    (code, msg) = self.getreply()
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
